CREATE TABLE PRODUTO(
	id INT(6) AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(30) NOT NULL,
	descricao VARCHAR(100),
	valor DECIMAL(8,2),
	id_categoria INT(6)
);

CREATE TABLE CATEGORIA(
	id INT(6) AUTO_INCREMENT PRIMARY KEY,
	descricao VARCHAR(30) NOT NULL
);

